// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAakFZgEGYKqpRpex9Tf2tB8ovV5pdlbs',
    appId: '1:351246581707:web:f4453568290b30f381404e',
    messagingSenderId: '351246581707',
    projectId: 'ecommerce-php-b99e3',
    authDomain: 'ecommerce-php-b99e3.firebaseapp.com',
    storageBucket: 'ecommerce-php-b99e3.firebasestorage.app',
    measurementId: 'G-XB17KTSVKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYt41pGdNnlRnq4bq5Xsvmsw-xFf_6cg',
    appId: '1:351246581707:android:73da7e9b15c52b3781404e',
    messagingSenderId: '351246581707',
    projectId: 'ecommerce-php-b99e3',
    storageBucket: 'ecommerce-php-b99e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvf-o6aHG9hC4WF1MzZQsg5mxNvdX3Cro',
    appId: '1:351246581707:ios:f3d23863749638ba81404e',
    messagingSenderId: '351246581707',
    projectId: 'ecommerce-php-b99e3',
    storageBucket: 'ecommerce-php-b99e3.firebasestorage.app',
    iosBundleId: 'com.example.gestionPedidosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvf-o6aHG9hC4WF1MzZQsg5mxNvdX3Cro',
    appId: '1:351246581707:ios:f3d23863749638ba81404e',
    messagingSenderId: '351246581707',
    projectId: 'ecommerce-php-b99e3',
    storageBucket: 'ecommerce-php-b99e3.firebasestorage.app',
    iosBundleId: 'com.example.gestionPedidosFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAakFZgEGYKqpRpex9Tf2tB8ovV5pdlbs',
    appId: '1:351246581707:web:1b39c5fd21b9e21b81404e',
    messagingSenderId: '351246581707',
    projectId: 'ecommerce-php-b99e3',
    authDomain: 'ecommerce-php-b99e3.firebaseapp.com',
    storageBucket: 'ecommerce-php-b99e3.firebasestorage.app',
    measurementId: 'G-N137FK3P81',
  );
}
